### ISSUE TITLE
Build errors with g++ 7.3

### ISSUE THREAD

**Issue by rhaist** [aerospike/aerospike-server#1]
Building the server with debian buster and g++ 7.3.0 gives multiple errors.

__________

**OS:** *Debian Testing (Buster)*

**Aerospike version:** *4.0.0.1-0-g997e3d0*
__________

```
base/thr_info.c: In function ‘info_get_services_x’:
base/thr_info.c:5371:35: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Werror=format-truncation=]
  snprintf(strip, sizeof(strip), ":%d", best_port);
                                   ^~
base/thr_info.c:5371:33: note: directive argument in the range [0, 2147483646]
  snprintf(strip, sizeof(strip), ":%d", best_port);
                                 ^~~~~
base/thr_info.c:5371:2: note: ‘snprintf’ output between 3 and 12 bytes into a destination of size 7
  snprintf(strip, sizeof(strip), ":%d", best_port);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

```
In file included from ../include/base/datamodel.h:52:0,
                 from geospatial/geospatial.cc:33:
../include/base/proto.h:167:16: error: flexible array member ‘as_proto_s::data’ not at end of ‘struct as_comp_proto_s’
  uint8_t  data[];
                ^
../include/base/proto.h:178:14: note: next member ‘uint64_t as_comp_proto_s::org_sz’ declared here
  uint64_t    org_sz;    // Original size of compressed data hold in 'data'
              ^~~~~~
../include/base/proto.h:176:16: note: in the definition of ‘struct as_comp_proto_s’
 typedef struct as_comp_proto_s {
                ^~~~~~~~~~~~~~~
../include/base/proto.h:167:16: error: flexible array member ‘as_proto_s::data’ not at end of ‘struct cl_msg_s’
  uint8_t  data[];
                ^
../include/base/proto.h:330:10: note: next member ‘as_msg cl_msg_s::msg’ declared here
  as_msg  msg;
          ^~~
../include/base/proto.h:328:16: note: in the definition of ‘struct cl_msg_s’
 typedef struct cl_msg_s {
                ^~~~~~~~
In file included from geospatial/geospatial.cc:33:0:
../include/base/datamodel.h:161:16: error: flexible array member ‘as_particle_s::data’ not at end of ‘struct as_bin_s’
  uint8_t  data[];
                ^
In file included from geospatial/geospatial.cc:33:0:
../include/base/datamodel.h:261:15: note: next member ‘as_particle* as_bin_s::particle’ declared here
  as_particle *particle; // for embedded particle this is value, not pointer
               ^~~~~~~~
../include/base/datamodel.h:259:8: note: in the definition of ‘struct as_bin_s’
 struct as_bin_s {
        ^~~~~~~~
../../make_in/Makefile.targets:16: recipe for target '../../target/Linux-x86_64/obj/geospatial/geospatial.o' failed

```

**Comment by kportertx** [comment]
The next release is patched to compile on Ubuntu 18.04 which currently uses GCC 7.3. In the meantime you can downgrade your GCC to compile:

On Ubuntu 17 I did the following to downgrade g++:
```
sudo apt install g++-6
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 20
sudo update-alternatives --config g++ # interactive step.
```

**Comment by karlhiramoto** [comment]
Also saw this on tag 4.0.0.4   Amazon linux2 (rpm based) https://aws.amazon.com/amazon-linux-2/

**Comment by kportertx** [comment]
This issue is independent of your package manager. The current code-base will not compile using GCC 7. This has already been addressed internally and will be released with 4.1.x. In the meantime you could use Amazon Linux 1 or downgrade g++ to version 6 and remake.

**Comment by psi-mankoski** [comment]
This issue is resolved starting with the Aerospike Server CE 4.1.0.1 release.
